---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passman-fe
  labels:
    name: passman-fe
    app: passman
spec:
  template:
    metadata:
      labels:
        name: passman-fe
    spec:
      containers:
        - name: passman-fe
          image: ghcr.io/nizam-chaudhary/passman-fe:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
  selector:
    matchLabels:
      name: passman-fe
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: passman-fe
spec:
  type: ClusterIP
  selector:
    name: passman-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: passman-fe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: passman.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: passman-fe
                port:
                  number: 80
