services:
  passman:
    image: passman:1.0.0
    container_name: passman
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.passman.loadbalancer.server.port=80
      - traefik.http.routers.passman.rule=Host(`localhost`)
    networks:
      - web

networks:
  web:
    external: true
